'use server'

import { revalidatePath, updateTag } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import { getCurrentUser } from './auth'
import { applyBalanceDelta } from './reference'
import { defaultDirectionForContribution } from '@/lib/balance-direction'
import type { TransactionType } from '../constants'
import {
  actionError,
  actionOk,
  runAction,
  type ActionResult,
} from './action-result'

export async function submitPayment(formData: FormData): Promise<ActionResult> {
  return runAction('submitPayment', async () => {
    const supabase = await createClient()
    const user = await getCurrentUser()

    if (!user) {
      return actionError('You must be logged in')
    }

    const transactionDate = formData.get('transaction_date') as string
    const bankTransactionId =
      (formData.get('bank_transaction_id') as string | null)?.trim() || null
    const amount = parseFloat(formData.get('amount') as string)
    const transactionType = formData.get('transaction_type') as TransactionType
    const description = formData.get('description') as string
    const loanIdRaw = (formData.get('loan_id') as string | null)?.trim() || null

    if (transactionType === 'loan_repayment' && !loanIdRaw) {
      return actionError('Pick the loan this repayment is for', 'loan_id')
    }

    // Auto-attribute to the submitter's canonical member row (matched by email).
    // Without this, the approved transaction ends up with member_id = null and
    // shows as "—" in the Member column. Admin can still override during
    // approval if the email doesn't match.
    let memberId: string | null = null
    if (user.email) {
      const { data: member } = await supabase
        .from('members')
        .select('id')
        .ilike('email', user.email)
        .maybeSingle()
      memberId = member?.id ?? null
    }

    // transaction_id is intentionally left unset: the canonical YYYYMMDD-NNN id
    // is generated by the trigger on `transactions` when this payment is
    // approved. The user only supplies the bank's own reference.
    const { error } = await supabase.from('pending_payments').insert({
      transaction_date: transactionDate,
      bank_transaction_id: bankTransactionId,
      amount,
      transaction_type: transactionType,
      description,
      submitted_by: user.id,
      member_id: memberId,
      loan_id: loanIdRaw,
      status: 'pending',
    })

    if (error) {
      return actionError(error.message)
    }

    revalidatePath('/dashboard')
    updateTag('dashboard')
    return actionOk(undefined, 'Payment submitted for review')
  })
}

export async function getPendingPayments() {
  const supabase = await createClient()
  const user = await getCurrentUser()

  if (!user || user.profile?.role !== 'admin') {
    throw new Error('Unauthorized')
  }

  // Disambiguate the FK: pending_payments has TWO references to profiles
  // (submitted_by and reviewed_by). The !submitted_by hint tells PostgREST
  // which one to follow. Aliased to `submitter` so the result reads cleanly.
  // Also embed the auto-matched member so the admin can see / override it.
  const { data, error } = await supabase
    .from('pending_payments')
    .select('*, submitter:profiles!submitted_by(full_name), member:member_id(id, name)')
    .eq('status', 'pending')
    .order('created_at', { ascending: false })

  if (error) throw new Error(error.message)
  return data
}

export async function getUserPayments() {
  const supabase = await createClient()
  const user = await getCurrentUser()

  if (!user) throw new Error('Not authenticated')

  const { data, error } = await supabase
    .from('pending_payments')
    .select('*')
    .eq('submitted_by', user.id)
    .order('created_at', { ascending: false })

  if (error) throw new Error(error.message)
  return data
}

/**
 * Approve a pending payment, optionally with edits.
 *
 * FormData fields:
 *   - id                 (required) — pending_payments.id
 *   - bank_transaction_id, transaction_date, amount, description (optional overrides)
 *
 * Each override replaces the corresponding field on the pending row when the
 * transaction is inserted. Missing/blank overrides fall back to the pending
 * row's stored value. The pending row itself is also patched so the audit
 * trail reflects the final values.
 */
export async function approvePayment(
  formData: FormData,
): Promise<ActionResult<{ balanceUpdateFailed: boolean }>> {
  return runAction('approvePayment', async () => {
    const supabase = await createClient()
    const user = await getCurrentUser()

    if (!user || user.profile?.role !== 'admin') {
      return actionError('Unauthorized')
    }

    const paymentId = (formData.get('id') as string | null)?.trim()
    if (!paymentId) return actionError('Missing pending payment id')

    const { data: payment, error: fetchError } = await supabase
      .from('pending_payments')
      .select('*')
      .eq('id', paymentId)
      .single()

    if (fetchError || !payment) {
      return actionError('Payment not found')
    }

    // Pull edits (anything blank falls back to the pending row's value).
    const rawBankTxnId = (formData.get('bank_transaction_id') as string | null)?.trim()
    const rawDate    = (formData.get('transaction_date') as string | null)?.trim()
    const rawAmount  = (formData.get('amount')           as string | null)?.trim()
    const rawDesc    = formData.get('description')       as string | null
    // member_id is a special case: '' means "explicit no member", and "__keep__"
    // means "use the pending row's existing member_id" (the dropdown's default).
    const rawMember  = formData.get('member_id')          as string | null

    const finalBankTxnId = rawBankTxnId || payment.bank_transaction_id || null
    const finalDate  = rawDate  || payment.transaction_date
    const finalAmount = rawAmount ? parseFloat(rawAmount) : Number(payment.amount)
    const finalDesc  = rawDesc !== null ? (rawDesc.trim() || null) : payment.description
    let finalMemberId =
      rawMember === null || rawMember === '__keep__'
        ? payment.member_id
        : rawMember === ''
          ? null
          : rawMember

    // Defensive auto-link: if we still don't have a member at approval time
    // (e.g., pending row was created before the submit-side fix), try to find
    // the submitter's member by joining profiles → auth.users.email → members.
    // Looks expensive but it's two cheap lookups and only runs when needed.
    if (finalMemberId == null && payment.submitted_by) {
      const { data: { user: approver } } = await supabase.auth.getUser()
      const { data: submitterProfile } = await supabase
        .from('profiles')
        .select('id, full_name')
        .eq('id', payment.submitted_by)
        .maybeSingle()
      void approver
      if (submitterProfile) {
        // Last-resort: match member.name to profile.full_name (handles cases
        // where members.email isn't seeded but profile.full_name and
        // members.name align).
        const { data: matchByName } = await supabase
          .from('members')
          .select('id')
          .ilike('name', submitterProfile.full_name ?? '')
          .maybeSingle()
        if (matchByName) finalMemberId = matchByName.id
      }
    }

    if (!Number.isFinite(finalAmount) || finalAmount <= 0) {
      return actionError('Amount must be a positive number', 'amount')
    }

    // transaction_id is left unset so the BEFORE INSERT trigger fills the
    // canonical YYYYMMDD-NNN value. The bank's reference travels separately.
    const { error: insertError } = await supabase.from('transactions').insert({
      transaction_date: finalDate,
      bank_transaction_id: finalBankTxnId,
      amount: finalAmount,
      transaction_type: payment.transaction_type,
      interest_source: payment.interest_source,
      member_id: finalMemberId,
      loan_id: payment.loan_id,
      description: finalDesc,
      created_by: payment.submitted_by,
      verified_by: user.id,
    })

    if (insertError) {
      return actionError(insertError.message)
    }

    // Mirror the final values onto the pending row so the audit trail shows
    // what was actually approved.
    const { error: updateError } = await supabase
      .from('pending_payments')
      .update({
        bank_transaction_id: finalBankTxnId,
        transaction_date: finalDate,
        amount: finalAmount,
        description: finalDesc,
        member_id: finalMemberId,
        status: 'approved',
        reviewed_by: user.id,
        reviewed_at: new Date().toISOString(),
      })
      .eq('id', paymentId)

    if (updateError) {
      return actionError(updateError.message)
    }

    const applyToBankBalance = formData.get('applyToBankBalance') === '1'
    const balanceDirectionRaw = formData.get('balanceDirection') as 'add' | 'subtract' | null
    let balanceUpdateFailed = false
    if (applyToBankBalance) {
      const direction =
        balanceDirectionRaw === 'add' || balanceDirectionRaw === 'subtract'
          ? balanceDirectionRaw
          : defaultDirectionForContribution(payment.transaction_type as TransactionType)
      const delta = direction === 'add' ? finalAmount : -finalAmount
      const result = await applyBalanceDelta(delta)
      if (!result.ok) {
        console.error('applyBalanceDelta failed for approvePayment:', result.error)
        balanceUpdateFailed = true
      }
    }

    revalidatePath('/admin/pending')
    revalidatePath('/admin')
    revalidatePath('/dashboard')
    revalidatePath('/admin/reference')
    updateTag('dashboard')
    return actionOk({ balanceUpdateFailed }, 'Payment approved and recorded')
  })
}

export async function rejectPayment(paymentId: string, notes: string): Promise<ActionResult> {
  return runAction('rejectPayment', async () => {
    const supabase = await createClient()
    const user = await getCurrentUser()

    if (!user || user.profile?.role !== 'admin') {
      return actionError('Unauthorized')
    }

    const { error } = await supabase
      .from('pending_payments')
      .update({
        status: 'rejected',
        admin_notes: notes,
        reviewed_by: user.id,
        reviewed_at: new Date().toISOString(),
      })
      .eq('id', paymentId)

    if (error) {
      return actionError(error.message)
    }

    revalidatePath('/admin/pending')
    return actionOk(undefined, 'Payment rejected')
  })
}
