-- =============================================================================
-- FCF Tracker — 2016 transactions seed
-- Source: '2016' sheet of FCF Latest one upto 6_07_2020.xlsx
--
-- Generated by scripts/generate-yearly-transactions.py — do not hand-edit.
-- Re-running is safe: every INSERT uses ON CONFLICT (transaction_id) DO NOTHING.
--
-- Rows: 62  (59 contributions + 3 bank-int + 0 loan-int)
-- Totals: contributions=₹74,000.00  bank_interest=₹704.00  loan_interest=₹0.00
--
-- member_id is resolved at INSERT time via the canonical email so this
-- works even after a clean DB rebuild (UUIDs change; emails don't).
-- =============================================================================

begin;

-- 1) Member contributions (59 rows)
insert into public.transactions
  (transaction_id, amount, contribution_type, interest_source, member_id, transaction_date, description) values
  ('SEED-2016-07-ANL', 2000.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2016-07-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2016-10-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2016-10-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2016-11-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2016-11-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2016-12-ANL', 5000.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2016-12-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2016-08-RAM', 2000.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2016-08-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2016-10-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2016-10-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2016-11-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2016-11-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2016-12-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2016-12-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2016-08-SNT', 2000.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2016-08-15', 'Chintalapalli Srinith'),
  ('SEED-2016-10-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2016-10-15', 'Chintalapalli Srinith'),
  ('SEED-2016-11-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2016-11-15', 'Chintalapalli Srinith'),
  ('SEED-2016-12-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2016-12-15', 'Chintalapalli Srinith'),
  ('SEED-2016-07-CHL', 1300.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2016-07-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2016-08-CHL', 700.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2016-08-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2016-09-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2016-09-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2016-11-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2016-11-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2016-12-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2016-12-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2016-08-DAS', 3000.00, 'contribution', null, (select id from public.members where email = 'bagavandas.g@gmail.com'), '2016-08-15', 'Bhagavan Das'),
  ('SEED-2016-10-DAS', 3000.00, 'contribution', null, (select id from public.members where email = 'bagavandas.g@gmail.com'), '2016-10-15', 'Bhagavan Das'),
  ('SEED-2016-09-HKR', 2000.00, 'contribution', null, (select id from public.members where email = 'hkjetti@gmail.com'), '2016-09-15', 'Jetty Harikrishna Krishna'),
  ('SEED-2016-10-HKR', 500.00, 'contribution', null, (select id from public.members where email = 'hkjetti@gmail.com'), '2016-10-15', 'Jetty Harikrishna Krishna'),
  ('SEED-2016-12-HKR', 2000.00, 'contribution', null, (select id from public.members where email = 'hkjetti@gmail.com'), '2016-12-15', 'Jetty Harikrishna Krishna'),
  ('SEED-2016-08-DLN', 2000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2016-08-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2016-10-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2016-10-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2016-11-DLN', 2000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2016-11-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2016-12-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2016-12-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2016-07-MAL', 200.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2016-07-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2016-10-MAL', 2300.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2016-10-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2016-11-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2016-11-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2016-12-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2016-12-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2016-08-SNL', 2000.00, 'contribution', null, (select id from public.members where email = 'mallisunilmca69@gmail.com'), '2016-08-15', 'Malli Sunil Kumar'),
  ('SEED-2016-12-SNL', 2000.00, 'contribution', null, (select id from public.members where email = 'mallisunilmca69@gmail.com'), '2016-12-15', 'Malli Sunil Kumar'),
  ('SEED-2016-07-PAR', 2000.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2016-07-15', 'Korrakuti Paramesh'),
  ('SEED-2016-10-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2016-10-15', 'Korrakuti Paramesh'),
  ('SEED-2016-11-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2016-11-15', 'Korrakuti Paramesh'),
  ('SEED-2016-12-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2016-12-15', 'Korrakuti Paramesh'),
  ('SEED-2016-07-PRS', 2000.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2016-07-15', 'Ponugoti Prasad'),
  ('SEED-2016-10-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2016-10-15', 'Ponugoti Prasad'),
  ('SEED-2016-11-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2016-11-15', 'Ponugoti Prasad'),
  ('SEED-2016-12-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2016-12-15', 'Ponugoti Prasad'),
  ('SEED-2016-09-SAM', 2000.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2016-09-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2016-10-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2016-10-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2016-11-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2016-11-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2016-12-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2016-12-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2016-10-SDP', 3500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2016-10-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2016-11-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2016-11-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2016-07-SHG', 2000.00, 'contribution', null, (select id from public.members where email = 'sheshagiri.gopathi@gmail.com'), '2016-07-15', 'Gopathi Sheshagiri'),
  ('SEED-2016-11-SHG', 1000.00, 'contribution', null, (select id from public.members where email = 'sheshagiri.gopathi@gmail.com'), '2016-11-15', 'Gopathi Sheshagiri'),
  ('SEED-2016-08-SRR', 2000.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2016-08-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2016-10-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2016-10-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2016-11-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2016-11-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2016-12-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2016-12-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2016-09-MED', 2500.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2016-09-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2016-11-MED', 1000.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2016-11-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2016-08-VEN', 2000.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2016-08-15', 'Kollai Venkateswarlu'),
  ('SEED-2016-10-VEN', 2000.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2016-10-15', 'Kollai Venkateswarlu'),
  ('SEED-2016-10-VSW', 2500.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2016-10-15', 'Oleti Viswanath'),
  ('SEED-2016-11-VSW', 500.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2016-11-15', 'Oleti Viswanath'),
  ('SEED-2016-12-VSW', 500.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2016-12-15', 'Oleti Viswanath')
on conflict (transaction_id) do nothing;

-- 2) Bank interest (3 rows)
insert into public.transactions
  (transaction_id, amount, contribution_type, interest_source, member_id, transaction_date, description) values
  ('SEED-BANK-2016-07', 9.00, 'interest', 'bank', null, '2016-07-28', 'Bank interest credited'),
  ('SEED-BANK-2016-10', 311.00, 'interest', 'bank', null, '2016-10-28', 'Bank interest credited'),
  ('SEED-BANK-2016-12', 384.00, 'interest', 'bank', null, '2016-12-28', 'Bank interest credited')
on conflict (transaction_id) do nothing;

commit;

-- Sanity check (uncomment to run after insert):
-- select contribution_type, interest_source, count(*), sum(amount)
--   from public.transactions
--  where transaction_date >= '2016-01-01' and transaction_date < '2017-01-01'
--  group by 1, 2 order by 1, 2;
