-- =============================================================================
-- FCF Tracker — 2017 transactions seed
-- Source: '2017' sheet of FCF Latest one upto 6_07_2020.xlsx
--
-- Generated by scripts/generate-yearly-transactions.py — do not hand-edit.
-- Re-running is safe: every INSERT uses ON CONFLICT (transaction_id) DO NOTHING.
--
-- Rows: 143  (138 contributions + 5 bank-int + 0 loan-int)
-- Totals: contributions=₹107,550.00  bank_interest=₹3,473.00  loan_interest=₹0.00
--
-- member_id is resolved at INSERT time via the canonical email so this
-- works even after a clean DB rebuild (UUIDs change; emails don't).
-- =============================================================================

begin;

-- 1) Member contributions (138 rows)
insert into public.transactions
  (transaction_id, amount, contribution_type, interest_source, member_id, transaction_date, description) values
  ('SEED-2017-01-ANL', 2000.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2017-01-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2017-02-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2017-02-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2017-03-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2017-03-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2017-04-ANL', 1000.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2017-04-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2017-05-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2017-05-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2017-06-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2017-06-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2017-07-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2017-07-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2017-09-ANL', 2000.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2017-09-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2017-11-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2017-11-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2017-12-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2017-12-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2017-01-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2017-01-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2017-02-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2017-02-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2017-03-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2017-03-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2017-04-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2017-04-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2017-05-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2017-05-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2017-06-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2017-06-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2017-07-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2017-07-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2017-08-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2017-08-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2017-09-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2017-09-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2017-10-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2017-10-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2017-11-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2017-11-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2017-12-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2017-12-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2017-03-SNT', 2000.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2017-03-15', 'Chintalapalli Srinith'),
  ('SEED-2017-06-SNT', 2000.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2017-06-15', 'Chintalapalli Srinith'),
  ('SEED-2017-10-SNT', 1000.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2017-10-15', 'Chintalapalli Srinith'),
  ('SEED-2017-11-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2017-11-15', 'Chintalapalli Srinith'),
  ('SEED-2017-12-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2017-12-15', 'Chintalapalli Srinith'),
  ('SEED-2017-01-CHL', 1500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2017-01-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2017-02-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2017-02-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2017-03-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2017-03-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2017-04-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2017-04-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2017-05-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2017-05-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2017-06-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2017-06-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2017-07-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2017-07-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2017-08-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2017-08-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2017-09-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2017-09-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2017-10-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2017-10-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2017-11-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2017-11-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2017-03-DAS', 3000.00, 'contribution', null, (select id from public.members where email = 'bagavandas.g@gmail.com'), '2017-03-15', 'Bhagavan Das'),
  ('SEED-2017-02-HKR', 2500.00, 'contribution', null, (select id from public.members where email = 'hkjetti@gmail.com'), '2017-02-15', 'Jetty Harikrishna Krishna'),
  ('SEED-2017-07-HKR', 3000.00, 'contribution', null, (select id from public.members where email = 'hkjetti@gmail.com'), '2017-07-15', 'Jetty Harikrishna Krishna'),
  ('SEED-2017-09-HKR', 500.00, 'contribution', null, (select id from public.members where email = 'hkjetti@gmail.com'), '2017-09-15', 'Jetty Harikrishna Krishna'),
  ('SEED-2017-10-HKR', 1000.00, 'contribution', null, (select id from public.members where email = 'hkjetti@gmail.com'), '2017-10-15', 'Jetty Harikrishna Krishna'),
  ('SEED-2017-11-HKR', 2000.00, 'contribution', null, (select id from public.members where email = 'hkjetti@gmail.com'), '2017-11-15', 'Jetty Harikrishna Krishna'),
  ('SEED-2017-01-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2017-01-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2017-02-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2017-02-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2017-03-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2017-03-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2017-04-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2017-04-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2017-05-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2017-05-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2017-06-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2017-06-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2017-07-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2017-07-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2017-01-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2017-01-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2017-02-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2017-02-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2017-03-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2017-03-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2017-04-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2017-04-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2017-05-MAL', 550.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2017-05-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2017-06-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2017-06-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2017-07-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2017-07-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2017-08-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2017-08-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2017-10-MAL', 1000.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2017-10-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2017-12-MAL', 1000.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2017-12-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2017-04-SNL', 1000.00, 'contribution', null, (select id from public.members where email = 'mallisunilmca69@gmail.com'), '2017-04-15', 'Malli Sunil Kumar'),
  ('SEED-2017-10-SNL', 1000.00, 'contribution', null, (select id from public.members where email = 'mallisunilmca69@gmail.com'), '2017-10-15', 'Malli Sunil Kumar'),
  ('SEED-2017-11-SNL', 2000.00, 'contribution', null, (select id from public.members where email = 'mallisunilmca69@gmail.com'), '2017-11-15', 'Malli Sunil Kumar'),
  ('SEED-2017-01-PAR', 1000.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2017-01-15', 'Korrakuti Paramesh'),
  ('SEED-2017-03-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2017-03-15', 'Korrakuti Paramesh'),
  ('SEED-2017-04-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2017-04-15', 'Korrakuti Paramesh'),
  ('SEED-2017-06-PAR', 1500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2017-06-15', 'Korrakuti Paramesh'),
  ('SEED-2017-08-PAR', 1000.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2017-08-15', 'Korrakuti Paramesh'),
  ('SEED-2017-10-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2017-10-15', 'Korrakuti Paramesh'),
  ('SEED-2017-11-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2017-11-15', 'Korrakuti Paramesh'),
  ('SEED-2017-12-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2017-12-15', 'Korrakuti Paramesh'),
  ('SEED-2017-01-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2017-01-15', 'Ponugoti Prasad'),
  ('SEED-2017-02-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2017-02-15', 'Ponugoti Prasad'),
  ('SEED-2017-03-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2017-03-15', 'Ponugoti Prasad'),
  ('SEED-2017-04-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2017-04-15', 'Ponugoti Prasad'),
  ('SEED-2017-05-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2017-05-15', 'Ponugoti Prasad'),
  ('SEED-2017-06-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2017-06-15', 'Ponugoti Prasad'),
  ('SEED-2017-07-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2017-07-15', 'Ponugoti Prasad'),
  ('SEED-2017-08-PRS', 1000.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2017-08-15', 'Ponugoti Prasad'),
  ('SEED-2017-10-PRS', 1000.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2017-10-15', 'Ponugoti Prasad'),
  ('SEED-2017-12-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2017-12-15', 'Ponugoti Prasad'),
  ('SEED-2017-01-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2017-01-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2017-02-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2017-02-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2017-03-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2017-03-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2017-04-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2017-04-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2017-05-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2017-05-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2017-06-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2017-06-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2017-07-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2017-07-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2017-08-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2017-08-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2017-09-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2017-09-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2017-10-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2017-10-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2017-11-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2017-11-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2017-12-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2017-12-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2017-01-SDP', 1000.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2017-01-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2017-02-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2017-02-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2017-03-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2017-03-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2017-04-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2017-04-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2017-06-SDP', 1500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2017-06-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2017-08-SDP', 1000.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2017-08-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2017-10-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2017-10-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2017-11-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2017-11-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2017-12-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2017-12-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2017-01-SHG', 1000.00, 'contribution', null, (select id from public.members where email = 'sheshagiri.gopathi@gmail.com'), '2017-01-15', 'Gopathi Sheshagiri'),
  ('SEED-2017-02-SHG', 1000.00, 'contribution', null, (select id from public.members where email = 'sheshagiri.gopathi@gmail.com'), '2017-02-15', 'Gopathi Sheshagiri'),
  ('SEED-2017-07-SHG', 2000.00, 'contribution', null, (select id from public.members where email = 'sheshagiri.gopathi@gmail.com'), '2017-07-15', 'Gopathi Sheshagiri'),
  ('SEED-2017-11-SHG', 2000.00, 'contribution', null, (select id from public.members where email = 'sheshagiri.gopathi@gmail.com'), '2017-11-15', 'Gopathi Sheshagiri'),
  ('SEED-2017-01-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2017-01-15', 'Duggireddy Sreenadh Reddy'),
  ('SEED-2017-02-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2017-02-15', 'Duggireddy Sreenadh Reddy'),
  ('SEED-2017-03-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2017-03-15', 'Duggireddy Sreenadh Reddy'),
  ('SEED-2017-04-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2017-04-15', 'Duggireddy Sreenadh Reddy'),
  ('SEED-2017-05-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2017-05-15', 'Duggireddy Sreenadh Reddy'),
  ('SEED-2017-06-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2017-06-15', 'Duggireddy Sreenadh Reddy'),
  ('SEED-2017-07-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2017-07-15', 'Duggireddy Sreenadh Reddy'),
  ('SEED-2017-08-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2017-08-15', 'Duggireddy Sreenadh Reddy'),
  ('SEED-2017-09-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2017-09-15', 'Duggireddy Sreenadh Reddy'),
  ('SEED-2017-10-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2017-10-15', 'Duggireddy Sreenadh Reddy'),
  ('SEED-2017-11-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2017-11-15', 'Duggireddy Sreenadh Reddy'),
  ('SEED-2017-12-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2017-12-15', 'Duggireddy Sreenadh Reddy'),
  ('SEED-2017-01-MED', 500.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2017-01-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2017-06-MED', 2000.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2017-06-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2017-02-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2017-02-15', 'Kollai Venkateswarlu'),
  ('SEED-2017-03-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2017-03-15', 'Kollai Venkateswarlu'),
  ('SEED-2017-04-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2017-04-15', 'Kollai Venkateswarlu'),
  ('SEED-2017-05-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2017-05-15', 'Kollai Venkateswarlu'),
  ('SEED-2017-06-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2017-06-15', 'Kollai Venkateswarlu'),
  ('SEED-2017-07-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2017-07-15', 'Kollai Venkateswarlu'),
  ('SEED-2017-09-VEN', 1000.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2017-09-15', 'Kollai Venkateswarlu'),
  ('SEED-2017-10-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2017-10-15', 'Kollai Venkateswarlu'),
  ('SEED-2017-11-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2017-11-15', 'Kollai Venkateswarlu'),
  ('SEED-2017-12-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2017-12-15', 'Kollai Venkateswarlu'),
  ('SEED-2017-01-VSW', 1000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2017-01-15', 'Oleti Viswanath'),
  ('SEED-2017-02-VSW', 1000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2017-02-15', 'Oleti Viswanath'),
  ('SEED-2017-03-VSW', 500.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2017-03-15', 'Oleti Viswanath'),
  ('SEED-2017-04-VSW', 500.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2017-04-15', 'Oleti Viswanath'),
  ('SEED-2017-06-VSW', 1000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2017-06-15', 'Oleti Viswanath'),
  ('SEED-2017-07-VSW', 1000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2017-07-15', 'Oleti Viswanath'),
  ('SEED-2017-09-VSW', 1000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2017-09-15', 'Oleti Viswanath')
on conflict (transaction_id) do nothing;

-- 2) Bank interest (5 rows)
insert into public.transactions
  (transaction_id, amount, contribution_type, interest_source, member_id, transaction_date, description) values
  ('SEED-BANK-2017-03', 500.00, 'interest', 'bank', null, '2017-03-28', 'Bank interest credited'),
  ('SEED-BANK-2017-06', 428.00, 'interest', 'bank', null, '2017-06-28', 'Bank interest credited'),
  ('SEED-BANK-2017-07', 2042.00, 'interest', 'bank', null, '2017-07-28', 'Bank interest credited'),
  ('SEED-BANK-2017-09', 368.00, 'interest', 'bank', null, '2017-09-28', 'Bank interest credited'),
  ('SEED-BANK-2017-12', 135.00, 'interest', 'bank', null, '2017-12-28', 'Bank interest credited')
on conflict (transaction_id) do nothing;

commit;

-- Sanity check (uncomment to run after insert):
-- select contribution_type, interest_source, count(*), sum(amount)
--   from public.transactions
--  where transaction_date >= '2017-01-01' and transaction_date < '2018-01-01'
--  group by 1, 2 order by 1, 2;
