-- =============================================================================
-- FCF Tracker — 2018 transactions seed
-- Source: '2018' sheet of FCF Latest one upto 6_07_2020.xlsx
--
-- Generated by scripts/generate-yearly-transactions.py — do not hand-edit.
-- Re-running is safe: every INSERT uses ON CONFLICT (transaction_id) DO NOTHING.
--
-- Rows: 120  (114 contributions + 6 bank-int + 0 loan-int)
-- Totals: contributions=₹94,000.00  bank_interest=₹19,988.00  loan_interest=₹0.00
--
-- member_id is resolved at INSERT time via the canonical email so this
-- works even after a clean DB rebuild (UUIDs change; emails don't).
-- =============================================================================

begin;

-- 1) Member contributions (114 rows)
insert into public.transactions
  (transaction_id, amount, contribution_type, interest_source, member_id, transaction_date, description) values
  ('SEED-2018-01-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2018-01-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2018-02-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2018-02-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2018-03-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2018-03-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2018-04-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2018-04-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2018-05-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2018-05-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2018-06-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2018-06-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2018-07-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2018-07-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2018-08-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2018-08-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2018-09-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2018-09-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2018-10-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2018-10-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2018-11-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2018-11-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2018-12-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2018-12-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2018-01-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2018-01-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2018-02-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2018-02-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2018-03-RAM', 1000.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2018-03-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2018-04-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2018-04-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2018-05-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2018-05-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2018-06-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2018-06-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2018-07-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2018-07-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2018-08-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2018-08-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2018-01-SNT', 1000.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2018-01-15', 'Chintalapalli Srinith'),
  ('SEED-2018-03-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2018-03-15', 'Chintalapalli Srinith'),
  ('SEED-2018-04-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2018-04-15', 'Chintalapalli Srinith'),
  ('SEED-2018-05-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2018-05-15', 'Chintalapalli Srinith'),
  ('SEED-2018-06-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2018-06-15', 'Chintalapalli Srinith'),
  ('SEED-2018-07-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2018-07-15', 'Chintalapalli Srinith'),
  ('SEED-2018-08-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2018-08-15', 'Chintalapalli Srinith'),
  ('SEED-2018-10-SNT', 1000.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2018-10-15', 'Chintalapalli Srinith'),
  ('SEED-2018-12-SNT', 1000.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2018-12-15', 'Chintalapalli Srinith'),
  ('SEED-2018-01-CHL', 2000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2018-01-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2018-03-CHL', 2000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2018-03-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2018-05-CHL', 2000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2018-05-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2018-07-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2018-07-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2018-08-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2018-08-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2018-09-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2018-09-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2018-10-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2018-10-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2018-11-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2018-11-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2018-12-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2018-12-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2018-02-HKR', 2000.00, 'contribution', null, (select id from public.members where email = 'hkjetti@gmail.com'), '2018-02-15', 'Jetty Harikrishna Krishna'),
  ('SEED-2018-09-HKR', 3000.00, 'contribution', null, (select id from public.members where email = 'hkjetti@gmail.com'), '2018-09-15', 'Jetty Harikrishna Krishna'),
  ('SEED-2018-01-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2018-01-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2018-03-DLN', 2000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2018-03-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2018-04-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2018-04-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2018-06-DLN', 1500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2018-06-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2018-01-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2018-01-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2018-02-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2018-02-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2018-03-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2018-03-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2018-05-MAL', 1000.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2018-05-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2018-06-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2018-06-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2018-07-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2018-07-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2018-08-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2018-08-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2018-09-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2018-09-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2018-10-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2018-10-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2018-11-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2018-11-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2018-12-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2018-12-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2018-06-SNL', 3000.00, 'contribution', null, (select id from public.members where email = 'mallisunilmca69@gmail.com'), '2018-06-15', 'Malli Sunil Kumar'),
  ('SEED-2018-01-PAR', 1000.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2018-01-15', 'Korrakuti Paramesh'),
  ('SEED-2018-03-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2018-03-15', 'Korrakuti Paramesh'),
  ('SEED-2018-04-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2018-04-15', 'Korrakuti Paramesh'),
  ('SEED-2018-05-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2018-05-15', 'Korrakuti Paramesh'),
  ('SEED-2018-06-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2018-06-15', 'Korrakuti Paramesh'),
  ('SEED-2018-07-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2018-07-15', 'Korrakuti Paramesh'),
  ('SEED-2018-08-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2018-08-15', 'Korrakuti Paramesh'),
  ('SEED-2018-10-PAR', 1000.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2018-10-15', 'Korrakuti Paramesh'),
  ('SEED-2018-12-PAR', 1000.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2018-12-15', 'Korrakuti Paramesh'),
  ('SEED-2018-01-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2018-01-15', 'Ponugoti Prasad'),
  ('SEED-2018-04-PRS', 2000.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2018-04-15', 'Ponugoti Prasad'),
  ('SEED-2018-06-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2018-06-15', 'Ponugoti Prasad'),
  ('SEED-2018-07-PRS', 1000.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2018-07-15', 'Ponugoti Prasad'),
  ('SEED-2018-12-PRS', 2000.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2018-12-15', 'Ponugoti Prasad'),
  ('SEED-2018-01-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2018-01-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2018-02-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2018-02-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2018-03-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2018-03-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2018-04-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2018-04-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2018-05-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2018-05-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2018-07-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2018-07-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2018-08-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2018-08-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2018-10-SAM', 1000.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2018-10-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2018-11-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2018-11-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2018-12-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2018-12-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2018-01-SDP', 1000.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2018-01-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2018-03-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2018-03-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2018-04-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2018-04-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2018-05-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2018-05-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2018-06-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2018-06-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2018-07-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2018-07-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2018-08-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2018-08-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2018-10-SDP', 1000.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2018-10-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2018-12-SDP', 1000.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2018-12-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2018-01-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2018-01-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2018-02-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2018-02-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2018-03-SRR', 1000.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2018-03-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2018-04-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2018-04-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2018-05-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2018-05-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2018-06-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2018-06-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2018-07-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2018-07-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2018-08-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2018-08-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2018-01-MED', 4000.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2018-01-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2018-10-MED', 4000.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2018-10-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2018-11-MED', 1000.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2018-11-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2018-12-MED', 500.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2018-12-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2018-01-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2018-01-15', 'Kollai Venkateswarlu'),
  ('SEED-2018-02-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2018-02-15', 'Kollai Venkateswarlu'),
  ('SEED-2018-03-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2018-03-15', 'Kollai Venkateswarlu'),
  ('SEED-2018-04-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2018-04-15', 'Kollai Venkateswarlu'),
  ('SEED-2018-06-VEN', 1000.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2018-06-15', 'Kollai Venkateswarlu'),
  ('SEED-2018-07-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2018-07-15', 'Kollai Venkateswarlu'),
  ('SEED-2018-08-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2018-08-15', 'Kollai Venkateswarlu'),
  ('SEED-2018-09-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2018-09-15', 'Kollai Venkateswarlu'),
  ('SEED-2018-10-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2018-10-15', 'Kollai Venkateswarlu'),
  ('SEED-2018-11-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2018-11-15', 'Kollai Venkateswarlu'),
  ('SEED-2018-01-VSW', 2000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2018-01-15', 'Oleti Viswanath'),
  ('SEED-2018-02-VSW', 1000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2018-02-15', 'Oleti Viswanath'),
  ('SEED-2018-07-VSW', 2000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2018-07-15', 'Oleti Viswanath')
on conflict (transaction_id) do nothing;

-- 2) Bank interest (6 rows)
insert into public.transactions
  (transaction_id, amount, contribution_type, interest_source, member_id, transaction_date, description) values
  ('SEED-BANK-2018-01', 1612.00, 'interest', 'bank', null, '2018-01-28', 'Bank interest credited'),
  ('SEED-BANK-2018-03', 402.00, 'interest', 'bank', null, '2018-03-28', 'Bank interest credited'),
  ('SEED-BANK-2018-04', 11458.00, 'interest', 'bank', null, '2018-04-28', 'Bank interest credited'),
  ('SEED-BANK-2018-06', 2018.00, 'interest', 'bank', null, '2018-06-28', 'Bank interest credited'),
  ('SEED-BANK-2018-09', 2135.00, 'interest', 'bank', null, '2018-09-28', 'Bank interest credited'),
  ('SEED-BANK-2018-12', 2363.00, 'interest', 'bank', null, '2018-12-28', 'Bank interest credited')
on conflict (transaction_id) do nothing;

commit;

-- Sanity check (uncomment to run after insert):
-- select contribution_type, interest_source, count(*), sum(amount)
--   from public.transactions
--  where transaction_date >= '2018-01-01' and transaction_date < '2019-01-01'
--  group by 1, 2 order by 1, 2;
