-- =============================================================================
-- FCF Tracker — 2019 transactions seed
-- Source: '2019' sheet of FCF Latest one upto 6_07_2020.xlsx
--
-- Generated by scripts/generate-yearly-transactions.py — do not hand-edit.
-- Re-running is safe: every INSERT uses ON CONFLICT (transaction_id) DO NOTHING.
--
-- Rows: 83  (76 contributions + 7 bank-int + 0 loan-int)
-- Totals: contributions=₹53,000.00  bank_interest=₹14,203.00  loan_interest=₹0.00
--
-- member_id is resolved at INSERT time via the canonical email so this
-- works even after a clean DB rebuild (UUIDs change; emails don't).
-- =============================================================================

begin;

-- 1) Member contributions (76 rows)
insert into public.transactions
  (transaction_id, amount, transaction_type, interest_source, member_id, transaction_date, description) values
  ('SEED-2019-01-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2019-01-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2019-02-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2019-02-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2019-03-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2019-03-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2019-04-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2019-04-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2019-05-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2019-05-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2019-06-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2019-06-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2019-07-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2019-07-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2019-08-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2019-08-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2019-09-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2019-09-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2019-10-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2019-10-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2019-11-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2019-11-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2019-12-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2019-12-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2019-01-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2019-01-15', 'Chintalapalli Srinith'),
  ('SEED-2019-02-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2019-02-15', 'Chintalapalli Srinith'),
  ('SEED-2019-03-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2019-03-15', 'Chintalapalli Srinith'),
  ('SEED-2019-04-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2019-04-15', 'Chintalapalli Srinith'),
  ('SEED-2019-05-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2019-05-15', 'Chintalapalli Srinith'),
  ('SEED-2019-06-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2019-06-15', 'Chintalapalli Srinith'),
  ('SEED-2019-07-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2019-07-15', 'Chintalapalli Srinith'),
  ('SEED-2019-08-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2019-08-15', 'Chintalapalli Srinith'),
  ('SEED-2019-09-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2019-09-15', 'Chintalapalli Srinith'),
  ('SEED-2019-10-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2019-10-15', 'Chintalapalli Srinith'),
  ('SEED-2019-11-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2019-11-15', 'Chintalapalli Srinith'),
  ('SEED-2019-12-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2019-12-15', 'Chintalapalli Srinith'),
  ('SEED-2019-03-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2019-03-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2019-04-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2019-04-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2019-05-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2019-05-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2019-07-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2019-07-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2019-10-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2019-10-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2019-04-HKR', 3000.00, 'contribution', null, (select id from public.members where email = 'hkjetti@gmail.com'), '2019-04-15', 'Jetty Harikrishna Krishna'),
  ('SEED-2019-02-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2019-02-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2019-04-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2019-04-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2019-06-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2019-06-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2019-07-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2019-07-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2019-11-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2019-11-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2019-01-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2019-01-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2019-02-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2019-02-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2019-03-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2019-03-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2019-04-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2019-04-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2019-05-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2019-05-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2019-06-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2019-06-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2019-07-MAL', 1000.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2019-07-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2019-09-MAL', 1000.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2019-09-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2019-11-MAL', 1000.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2019-11-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2019-12-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2019-12-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2019-02-SNL', 5000.00, 'contribution', null, (select id from public.members where email = 'mallisunilmca69@gmail.com'), '2019-02-15', 'Malli Sunil Kumar'),
  ('SEED-2019-01-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2019-01-15', 'Korrakuti Paramesh'),
  ('SEED-2019-02-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2019-02-15', 'Korrakuti Paramesh'),
  ('SEED-2019-03-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2019-03-15', 'Korrakuti Paramesh'),
  ('SEED-2019-04-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2019-04-15', 'Korrakuti Paramesh'),
  ('SEED-2019-05-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2019-05-15', 'Korrakuti Paramesh'),
  ('SEED-2019-06-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2019-06-15', 'Korrakuti Paramesh'),
  ('SEED-2019-07-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2019-07-15', 'Korrakuti Paramesh'),
  ('SEED-2019-08-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2019-08-15', 'Korrakuti Paramesh'),
  ('SEED-2019-09-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2019-09-15', 'Korrakuti Paramesh'),
  ('SEED-2019-10-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2019-10-15', 'Korrakuti Paramesh'),
  ('SEED-2019-11-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2019-11-15', 'Korrakuti Paramesh'),
  ('SEED-2019-12-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2019-12-15', 'Korrakuti Paramesh'),
  ('SEED-2019-02-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2019-02-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2019-03-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2019-03-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2019-11-SAM', 1000.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2019-11-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2019-01-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2019-01-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2019-02-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2019-02-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2019-03-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2019-03-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2019-04-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2019-04-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2019-05-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2019-05-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2019-06-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2019-06-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2019-07-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2019-07-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2019-08-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2019-08-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2019-09-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2019-09-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2019-10-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2019-10-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2019-11-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2019-11-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2019-12-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2019-12-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2019-02-MED', 1000.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2019-02-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2019-03-MED', 1000.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2019-03-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2019-11-MED', 3000.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2019-11-15', 'Meda Sunil Kumar Reddy')
on conflict (transaction_id) do nothing;

-- 2) Bank interest (7 rows)
insert into public.transactions
  (transaction_id, amount, transaction_type, interest_source, member_id, transaction_date, description) values
  ('SEED-BANK-2019-02', 1600.00, 'interest', 'bank', null, '2019-02-28', 'Bank interest credited'),
  ('SEED-BANK-2019-03', 2169.00, 'interest', 'bank', null, '2019-03-28', 'Bank interest credited'),
  ('SEED-BANK-2019-06', 1370.00, 'interest', 'bank', null, '2019-06-28', 'Bank interest credited'),
  ('SEED-BANK-2019-07', 4666.00, 'interest', 'bank', null, '2019-07-28', 'Bank interest credited'),
  ('SEED-BANK-2019-09', 1813.00, 'interest', 'bank', null, '2019-09-28', 'Bank interest credited'),
  ('SEED-BANK-2019-11', 533.00, 'interest', 'bank', null, '2019-11-28', 'Bank interest credited'),
  ('SEED-BANK-2019-12', 2052.00, 'interest', 'bank', null, '2019-12-28', 'Bank interest credited')
on conflict (transaction_id) do nothing;

commit;

-- Sanity check (uncomment to run after insert):
-- select transaction_type, interest_source, count(*), sum(amount)
--   from public.transactions
--  where transaction_date >= '2019-01-01' and transaction_date < '2020-01-01'
--  group by 1, 2 order by 1, 2;
