-- =============================================================================
-- FCF Tracker — 2020 transactions seed
-- Source: '2020' sheet of FCF Latest one upto 6_07_2020.xlsx
--
-- Generated by scripts/generate-yearly-transactions.py — do not hand-edit.
-- Re-running is safe: every INSERT uses ON CONFLICT (transaction_id) DO NOTHING.
--
-- Rows: 131  (126 contributions + 5 bank-int + 0 loan-int)
-- Totals: contributions=₹109,405.00  bank_interest=₹11,872.00  loan_interest=₹0.00
--
-- member_id is resolved at INSERT time via the canonical email so this
-- works even after a clean DB rebuild (UUIDs change; emails don't).
-- =============================================================================

begin;

-- 1) Member contributions (126 rows)
insert into public.transactions
  (transaction_id, amount, transaction_type, interest_source, member_id, transaction_date, description) values
  ('SEED-2020-01-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2020-01-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2020-02-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2020-02-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2020-03-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2020-03-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2020-05-ANL', 2000.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2020-05-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2020-10-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2020-10-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2020-11-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2020-11-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2020-12-ANL', 1000.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2020-12-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2020-04-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2020-04-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2020-05-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2020-05-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2020-08-RAM', 1000.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2020-08-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2020-10-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2020-10-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2020-11-RAM', 1000.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2020-11-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2020-12-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2020-12-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2020-01-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2020-01-15', 'Chintalapalli Srinith'),
  ('SEED-2020-02-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2020-02-15', 'Chintalapalli Srinith'),
  ('SEED-2020-03-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2020-03-15', 'Chintalapalli Srinith'),
  ('SEED-2020-04-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2020-04-15', 'Chintalapalli Srinith'),
  ('SEED-2020-05-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2020-05-15', 'Chintalapalli Srinith'),
  ('SEED-2020-06-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2020-06-15', 'Chintalapalli Srinith'),
  ('SEED-2020-07-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2020-07-15', 'Chintalapalli Srinith'),
  ('SEED-2020-08-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2020-08-15', 'Chintalapalli Srinith'),
  ('SEED-2020-09-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2020-09-15', 'Chintalapalli Srinith'),
  ('SEED-2020-10-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2020-10-15', 'Chintalapalli Srinith'),
  ('SEED-2020-11-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2020-11-15', 'Chintalapalli Srinith'),
  ('SEED-2020-12-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2020-12-15', 'Chintalapalli Srinith'),
  ('SEED-2020-03-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2020-03-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2020-05-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2020-05-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2020-06-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2020-06-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2020-07-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2020-07-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2020-10-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2020-10-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2020-03-DAS', 500.00, 'contribution', null, (select id from public.members where email = 'bagavandas.g@gmail.com'), '2020-03-15', 'Bhagavan Das'),
  ('SEED-2020-04-DAS', 500.00, 'contribution', null, (select id from public.members where email = 'bagavandas.g@gmail.com'), '2020-04-15', 'Bhagavan Das'),
  ('SEED-2020-05-DAS', 1000.00, 'contribution', null, (select id from public.members where email = 'bagavandas.g@gmail.com'), '2020-05-15', 'Bhagavan Das'),
  ('SEED-2020-07-DAS', 2000.00, 'contribution', null, (select id from public.members where email = 'bagavandas.g@gmail.com'), '2020-07-15', 'Bhagavan Das'),
  ('SEED-2020-07-HKR', 6000.00, 'contribution', null, (select id from public.members where email = 'hkjetti@gmail.com'), '2020-07-15', 'Jetty Harikrishna Krishna'),
  ('SEED-2020-01-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2020-01-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2020-03-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2020-03-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2020-04-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2020-04-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2020-05-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2020-05-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2020-07-DLN', 1400.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2020-07-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2020-11-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2020-11-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2020-12-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2020-12-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2020-01-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2020-01-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2020-02-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2020-02-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2020-03-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2020-03-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2020-04-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2020-04-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2020-05-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2020-05-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2020-08-MAL', 1000.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2020-08-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2020-09-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2020-09-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2020-10-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2020-10-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2020-11-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2020-11-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2020-01-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2020-01-15', 'Korrakuti Paramesh'),
  ('SEED-2020-02-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2020-02-15', 'Korrakuti Paramesh'),
  ('SEED-2020-03-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2020-03-15', 'Korrakuti Paramesh'),
  ('SEED-2020-04-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2020-04-15', 'Korrakuti Paramesh'),
  ('SEED-2020-05-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2020-05-15', 'Korrakuti Paramesh'),
  ('SEED-2020-06-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2020-06-15', 'Korrakuti Paramesh'),
  ('SEED-2020-07-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2020-07-15', 'Korrakuti Paramesh'),
  ('SEED-2020-08-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2020-08-15', 'Korrakuti Paramesh'),
  ('SEED-2020-09-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2020-09-15', 'Korrakuti Paramesh'),
  ('SEED-2020-10-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2020-10-15', 'Korrakuti Paramesh'),
  ('SEED-2020-11-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2020-11-15', 'Korrakuti Paramesh'),
  ('SEED-2020-12-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2020-12-15', 'Korrakuti Paramesh'),
  ('SEED-2020-03-PRS', 10000.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2020-03-15', 'Ponugoti Prasad'),
  ('SEED-2020-12-PRS', 2000.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2020-12-15', 'Ponugoti Prasad'),
  ('SEED-2020-01-SAM', 1000.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2020-01-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2020-10-SAM', 1000.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2020-10-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2020-01-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2020-01-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2020-02-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2020-02-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2020-03-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2020-03-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2020-04-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2020-04-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2020-05-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2020-05-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2020-06-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2020-06-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2020-07-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2020-07-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2020-08-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2020-08-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2020-09-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2020-09-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2020-10-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2020-10-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2020-11-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2020-11-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2020-12-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2020-12-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2020-05-SRR', 1000.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2020-05-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2020-07-SRR', 1000.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2020-07-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2020-08-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2020-08-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2020-09-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2020-09-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2020-10-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2020-10-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2020-11-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2020-11-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2020-12-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2020-12-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2020-03-MED', 4000.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2020-03-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2020-07-MED', 1000.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2020-07-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2020-10-MED', 2000.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2020-10-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2020-03-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2020-03-15', 'Kollai Venkateswarlu'),
  ('SEED-2020-04-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2020-04-15', 'Kollai Venkateswarlu'),
  ('SEED-2020-05-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2020-05-15', 'Kollai Venkateswarlu'),
  ('SEED-2020-06-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2020-06-15', 'Kollai Venkateswarlu'),
  ('SEED-2020-07-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2020-07-15', 'Kollai Venkateswarlu'),
  ('SEED-2020-08-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2020-08-15', 'Kollai Venkateswarlu'),
  ('SEED-2020-09-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2020-09-15', 'Kollai Venkateswarlu'),
  ('SEED-2020-10-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2020-10-15', 'Kollai Venkateswarlu'),
  ('SEED-2020-11-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2020-11-15', 'Kollai Venkateswarlu'),
  ('SEED-2020-12-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2020-12-15', 'Kollai Venkateswarlu'),
  ('SEED-2020-05-VSW', 5000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2020-05-15', 'Oleti Viswanath'),
  ('SEED-2020-07-VSW', 1000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2020-07-15', 'Oleti Viswanath'),
  ('SEED-2020-09-VSW', 1000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2020-09-15', 'Oleti Viswanath'),
  ('SEED-2020-12-VSW', 1000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2020-12-15', 'Oleti Viswanath'),
  ('SEED-2020-03-LXM', 1000.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2020-03-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2020-04-LXM', 1000.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2020-04-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2020-05-LXM', 1000.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2020-05-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2020-06-LXM', 1000.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2020-06-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2020-07-LXM', 1000.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2020-07-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2020-08-LXM', 1000.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2020-08-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2020-09-LXM', 1000.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2020-09-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2020-10-LXM', 1000.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2020-10-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2020-11-LXM', 1000.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2020-11-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2020-12-LXM', 1000.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2020-12-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2020-03-PRK', 1000.00, 'contribution', null, (select id from public.members where email = 'prakash.mca42@gmail.com'), '2020-03-15', 'Prakash'),
  ('SEED-2020-05-PRK', 500.00, 'contribution', null, (select id from public.members where email = 'prakash.mca42@gmail.com'), '2020-05-15', 'Prakash'),
  ('SEED-2020-06-PRK', 500.00, 'contribution', null, (select id from public.members where email = 'prakash.mca42@gmail.com'), '2020-06-15', 'Prakash'),
  ('SEED-2020-07-PRK', 1000.00, 'contribution', null, (select id from public.members where email = 'prakash.mca42@gmail.com'), '2020-07-15', 'Prakash'),
  ('SEED-2020-10-PRK', 500.00, 'contribution', null, (select id from public.members where email = 'prakash.mca42@gmail.com'), '2020-10-15', 'Prakash'),
  ('SEED-2020-11-PRK', 500.00, 'contribution', null, (select id from public.members where email = 'prakash.mca42@gmail.com'), '2020-11-15', 'Prakash'),
  ('SEED-2020-12-PRK', 500.00, 'contribution', null, (select id from public.members where email = 'prakash.mca42@gmail.com'), '2020-12-15', 'Prakash'),
  ('SEED-2020-07-TRN', 1000.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2020-07-15', 'Panditi Trinath Gupta'),
  ('SEED-2020-09-TRN', 500.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2020-09-15', 'Panditi Trinath Gupta'),
  ('SEED-2020-10-TRN', 505.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2020-10-15', 'Panditi Trinath Gupta'),
  ('SEED-2020-11-TRN', 500.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2020-11-15', 'Panditi Trinath Gupta'),
  ('SEED-2020-12-TRN', 500.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2020-12-15', 'Panditi Trinath Gupta'),
  ('SEED-2020-12-SUD', 1000.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2020-12-15', 'Koppavarapu Sudhakar')
on conflict (transaction_id) do nothing;

-- 2) Bank interest (5 rows)
insert into public.transactions
  (transaction_id, amount, transaction_type, interest_source, member_id, transaction_date, description) values
  ('SEED-BANK-2020-03', 2243.00, 'interest', 'bank', null, '2020-03-28', 'Bank interest credited'),
  ('SEED-BANK-2020-06', 1547.00, 'interest', 'bank', null, '2020-06-28', 'Bank interest credited'),
  ('SEED-BANK-2020-07', 3000.00, 'interest', 'bank', null, '2020-07-28', 'Bank interest credited'),
  ('SEED-BANK-2020-10', 1752.00, 'interest', 'bank', null, '2020-10-28', 'Bank interest credited'),
  ('SEED-BANK-2020-12', 3330.00, 'interest', 'bank', null, '2020-12-28', 'Bank interest credited')
on conflict (transaction_id) do nothing;

commit;

-- Sanity check (uncomment to run after insert):
-- select transaction_type, interest_source, count(*), sum(amount)
--   from public.transactions
--  where transaction_date >= '2020-01-01' and transaction_date < '2021-01-01'
--  group by 1, 2 order by 1, 2;
