-- =============================================================================
-- FCF Tracker — 2022 transactions seed
-- Source: '2022' sheet of FCF Latest one upto 6_07_2020.xlsx
--
-- Generated by scripts/generate-yearly-transactions.py — do not hand-edit.
-- Re-running is safe: every INSERT uses ON CONFLICT (transaction_id) DO NOTHING.
--
-- Rows: 130  (121 contributions + 9 bank-int + 0 loan-int)
-- Totals: contributions=₹75,600.00  bank_interest=₹11,912.00  loan_interest=₹0.00
--
-- member_id is resolved at INSERT time via the canonical email so this
-- works even after a clean DB rebuild (UUIDs change; emails don't).
-- =============================================================================

begin;

-- 1) Member contributions (121 rows)
insert into public.transactions
  (transaction_id, amount, transaction_type, interest_source, member_id, transaction_date, description) values
  ('SEED-2022-01-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2022-01-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2022-06-RAM', 1000.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2022-06-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2022-08-RAM', 500.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2022-08-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2022-01-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2022-01-15', 'Chintalapalli Srinith'),
  ('SEED-2022-02-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2022-02-15', 'Chintalapalli Srinith'),
  ('SEED-2022-03-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2022-03-15', 'Chintalapalli Srinith'),
  ('SEED-2022-04-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2022-04-15', 'Chintalapalli Srinith'),
  ('SEED-2022-05-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2022-05-15', 'Chintalapalli Srinith'),
  ('SEED-2022-06-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2022-06-15', 'Chintalapalli Srinith'),
  ('SEED-2022-07-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2022-07-15', 'Chintalapalli Srinith'),
  ('SEED-2022-08-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2022-08-15', 'Chintalapalli Srinith'),
  ('SEED-2022-09-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2022-09-15', 'Chintalapalli Srinith'),
  ('SEED-2022-11-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2022-11-15', 'Chintalapalli Srinith'),
  ('SEED-2022-12-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2022-12-15', 'Chintalapalli Srinith'),
  ('SEED-2022-01-CHL', 1000.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2022-01-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2022-02-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2022-02-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2022-03-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2022-03-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2022-07-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2022-07-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2022-02-DAS', 500.00, 'contribution', null, (select id from public.members where email = 'bagavandas.g@gmail.com'), '2022-02-15', 'Bhagavan Das'),
  ('SEED-2022-03-DAS', 1000.00, 'contribution', null, (select id from public.members where email = 'bagavandas.g@gmail.com'), '2022-03-15', 'Bhagavan Das'),
  ('SEED-2022-06-DAS', 1000.00, 'contribution', null, (select id from public.members where email = 'bagavandas.g@gmail.com'), '2022-06-15', 'Bhagavan Das'),
  ('SEED-2022-01-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2022-01-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2022-02-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2022-02-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2022-03-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2022-03-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2022-05-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2022-05-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2022-06-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2022-06-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2022-07-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2022-07-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2022-08-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2022-08-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2022-09-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2022-09-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2022-11-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2022-11-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2022-12-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2022-12-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2022-02-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2022-02-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2022-03-MAL', 500.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2022-03-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2022-07-MAL', 1000.00, 'contribution', null, (select id from public.members where email = 'malli.chindukuri@gmail.com'), '2022-07-15', 'Chindukuri Mallikarjuna'),
  ('SEED-2022-01-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2022-01-15', 'Korrakuti Paramesh'),
  ('SEED-2022-02-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2022-02-15', 'Korrakuti Paramesh'),
  ('SEED-2022-03-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2022-03-15', 'Korrakuti Paramesh'),
  ('SEED-2022-04-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2022-04-15', 'Korrakuti Paramesh'),
  ('SEED-2022-05-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2022-05-15', 'Korrakuti Paramesh'),
  ('SEED-2022-06-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2022-06-15', 'Korrakuti Paramesh'),
  ('SEED-2022-07-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2022-07-15', 'Korrakuti Paramesh'),
  ('SEED-2022-08-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2022-08-15', 'Korrakuti Paramesh'),
  ('SEED-2022-09-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2022-09-15', 'Korrakuti Paramesh'),
  ('SEED-2022-11-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2022-11-15', 'Korrakuti Paramesh'),
  ('SEED-2022-12-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2022-12-15', 'Korrakuti Paramesh'),
  ('SEED-2022-01-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2022-01-15', 'Ponugoti Prasad'),
  ('SEED-2022-02-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2022-02-15', 'Ponugoti Prasad'),
  ('SEED-2022-03-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2022-03-15', 'Ponugoti Prasad'),
  ('SEED-2022-04-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2022-04-15', 'Ponugoti Prasad'),
  ('SEED-2022-05-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2022-05-15', 'Ponugoti Prasad'),
  ('SEED-2022-06-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2022-06-15', 'Ponugoti Prasad'),
  ('SEED-2022-07-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2022-07-15', 'Ponugoti Prasad'),
  ('SEED-2022-08-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2022-08-15', 'Ponugoti Prasad'),
  ('SEED-2022-09-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2022-09-15', 'Ponugoti Prasad'),
  ('SEED-2022-11-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2022-11-15', 'Ponugoti Prasad'),
  ('SEED-2022-12-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2022-12-15', 'Ponugoti Prasad'),
  ('SEED-2022-02-SAM', 1000.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2022-02-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2022-03-SAM', 1000.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2022-03-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2022-06-SAM', 1000.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2022-06-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2022-07-SAM', 1000.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2022-07-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2022-08-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2022-08-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2022-09-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2022-09-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2022-01-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2022-01-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2022-02-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2022-02-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2022-03-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2022-03-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2022-04-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2022-04-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2022-05-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2022-05-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2022-06-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2022-06-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2022-07-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2022-07-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2022-08-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2022-08-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2022-09-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2022-09-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2022-11-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2022-11-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2022-12-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2022-12-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2022-01-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2022-01-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2022-02-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2022-02-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2022-03-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2022-03-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2022-04-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2022-04-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2022-05-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2022-05-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2022-06-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2022-06-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2022-07-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2022-07-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2022-08-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2022-08-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2022-09-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2022-09-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2022-11-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2022-11-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2022-12-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2022-12-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2022-03-MED', 4600.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2022-03-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2022-01-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2022-01-15', 'Kollai Venkateswarlu'),
  ('SEED-2022-02-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2022-02-15', 'Kollai Venkateswarlu'),
  ('SEED-2022-03-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2022-03-15', 'Kollai Venkateswarlu'),
  ('SEED-2022-04-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2022-04-15', 'Kollai Venkateswarlu'),
  ('SEED-2022-05-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2022-05-15', 'Kollai Venkateswarlu'),
  ('SEED-2022-06-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2022-06-15', 'Kollai Venkateswarlu'),
  ('SEED-2022-08-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2022-08-15', 'Kollai Venkateswarlu'),
  ('SEED-2022-09-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2022-09-15', 'Kollai Venkateswarlu'),
  ('SEED-2022-11-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2022-11-15', 'Kollai Venkateswarlu'),
  ('SEED-2022-12-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2022-12-15', 'Kollai Venkateswarlu'),
  ('SEED-2022-01-VSW', 500.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2022-01-15', 'Oleti Viswanath'),
  ('SEED-2022-02-VSW', 500.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2022-02-15', 'Oleti Viswanath'),
  ('SEED-2022-04-VSW', 1000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2022-04-15', 'Oleti Viswanath'),
  ('SEED-2022-06-VSW', 1000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2022-06-15', 'Oleti Viswanath'),
  ('SEED-2022-01-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2022-01-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2022-02-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2022-02-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2022-03-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2022-03-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2022-04-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2022-04-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2022-05-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2022-05-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2022-06-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2022-06-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2022-07-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2022-07-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2022-08-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2022-08-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2022-09-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2022-09-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2022-11-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2022-11-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2022-12-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2022-12-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2022-02-TRN', 1000.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2022-02-15', 'Panditi Trinath Gupta'),
  ('SEED-2022-03-TRN', 1000.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2022-03-15', 'Panditi Trinath Gupta'),
  ('SEED-2022-09-TRN', 3000.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2022-09-15', 'Panditi Trinath Gupta'),
  ('SEED-2022-01-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2022-01-15', 'Koppavarapu Sudhakar'),
  ('SEED-2022-02-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2022-02-15', 'Koppavarapu Sudhakar'),
  ('SEED-2022-03-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2022-03-15', 'Koppavarapu Sudhakar'),
  ('SEED-2022-05-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2022-05-15', 'Koppavarapu Sudhakar'),
  ('SEED-2022-06-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2022-06-15', 'Koppavarapu Sudhakar'),
  ('SEED-2022-08-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2022-08-15', 'Koppavarapu Sudhakar'),
  ('SEED-2022-09-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2022-09-15', 'Koppavarapu Sudhakar'),
  ('SEED-2022-11-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2022-11-15', 'Koppavarapu Sudhakar')
on conflict (transaction_id) do nothing;

-- 2) Bank interest (9 rows)
insert into public.transactions
  (transaction_id, amount, transaction_type, interest_source, member_id, transaction_date, description) values
  ('SEED-BANK-2022-01', 1200.00, 'interest', 'bank', null, '2022-01-28', 'Bank interest credited'),
  ('SEED-BANK-2022-02', 1200.00, 'interest', 'bank', null, '2022-02-28', 'Bank interest credited'),
  ('SEED-BANK-2022-03', 1823.00, 'interest', 'bank', null, '2022-03-28', 'Bank interest credited'),
  ('SEED-BANK-2022-04', 600.00, 'interest', 'bank', null, '2022-04-28', 'Bank interest credited'),
  ('SEED-BANK-2022-05', 600.00, 'interest', 'bank', null, '2022-05-28', 'Bank interest credited'),
  ('SEED-BANK-2022-06', 3789.00, 'interest', 'bank', null, '2022-06-28', 'Bank interest credited'),
  ('SEED-BANK-2022-07', 600.00, 'interest', 'bank', null, '2022-07-28', 'Bank interest credited'),
  ('SEED-BANK-2022-08', 600.00, 'interest', 'bank', null, '2022-08-28', 'Bank interest credited'),
  ('SEED-BANK-2022-09', 1500.00, 'interest', 'bank', null, '2022-09-28', 'Bank interest credited')
on conflict (transaction_id) do nothing;

commit;

-- Sanity check (uncomment to run after insert):
-- select transaction_type, interest_source, count(*), sum(amount)
--   from public.transactions
--  where transaction_date >= '2022-01-01' and transaction_date < '2023-01-01'
--  group by 1, 2 order by 1, 2;
