-- =============================================================================
-- FCF Tracker — 2023 transactions seed
-- Source: '2023' sheet of FCF Latest one upto 6_07_2020.xlsx
--
-- Generated by scripts/generate-yearly-transactions.py — do not hand-edit.
-- Re-running is safe: every INSERT uses ON CONFLICT (transaction_id) DO NOTHING.
--
-- Rows: 105  (104 contributions + 1 bank-int + 0 loan-int)
-- Totals: contributions=₹60,500.00  bank_interest=₹600.00  loan_interest=₹0.00
--
-- member_id is resolved at INSERT time via the canonical email so this
-- works even after a clean DB rebuild (UUIDs change; emails don't).
-- =============================================================================

begin;

-- 1) Member contributions (104 rows)
insert into public.transactions
  (transaction_id, amount, contribution_type, interest_source, member_id, transaction_date, description) values
  ('SEED-2023-10-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2023-10-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2023-11-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2023-11-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2023-12-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2023-12-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2023-06-RAM', 3000.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2023-06-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2023-01-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2023-01-15', 'Chintalapalli Srinith'),
  ('SEED-2023-02-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2023-02-15', 'Chintalapalli Srinith'),
  ('SEED-2023-03-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2023-03-15', 'Chintalapalli Srinith'),
  ('SEED-2023-05-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2023-05-15', 'Chintalapalli Srinith'),
  ('SEED-2023-06-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2023-06-15', 'Chintalapalli Srinith'),
  ('SEED-2023-07-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2023-07-15', 'Chintalapalli Srinith'),
  ('SEED-2023-08-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2023-08-15', 'Chintalapalli Srinith'),
  ('SEED-2023-09-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2023-09-15', 'Chintalapalli Srinith'),
  ('SEED-2023-10-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2023-10-15', 'Chintalapalli Srinith'),
  ('SEED-2023-11-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2023-11-15', 'Chintalapalli Srinith'),
  ('SEED-2023-12-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2023-12-15', 'Chintalapalli Srinith'),
  ('SEED-2023-04-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2023-04-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2023-06-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2023-06-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2023-07-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2023-07-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2023-08-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2023-08-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2023-09-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2023-09-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2023-10-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2023-10-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2023-11-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2023-11-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2023-12-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2023-12-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2023-02-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2023-02-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2023-03-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2023-03-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2023-04-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2023-04-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2023-05-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2023-05-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2023-06-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2023-06-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2023-07-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2023-07-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2023-09-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2023-09-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2023-10-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2023-10-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2023-11-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2023-11-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2023-12-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2023-12-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2023-01-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2023-01-15', 'Korrakuti Paramesh'),
  ('SEED-2023-02-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2023-02-15', 'Korrakuti Paramesh'),
  ('SEED-2023-03-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2023-03-15', 'Korrakuti Paramesh'),
  ('SEED-2023-05-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2023-05-15', 'Korrakuti Paramesh'),
  ('SEED-2023-06-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2023-06-15', 'Korrakuti Paramesh'),
  ('SEED-2023-07-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2023-07-15', 'Korrakuti Paramesh'),
  ('SEED-2023-08-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2023-08-15', 'Korrakuti Paramesh'),
  ('SEED-2023-09-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2023-09-15', 'Korrakuti Paramesh'),
  ('SEED-2023-10-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2023-10-15', 'Korrakuti Paramesh'),
  ('SEED-2023-11-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2023-11-15', 'Korrakuti Paramesh'),
  ('SEED-2023-12-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2023-12-15', 'Korrakuti Paramesh'),
  ('SEED-2023-01-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2023-01-15', 'Ponugoti Prasad'),
  ('SEED-2023-02-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2023-02-15', 'Ponugoti Prasad'),
  ('SEED-2023-03-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2023-03-15', 'Ponugoti Prasad'),
  ('SEED-2023-05-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2023-05-15', 'Ponugoti Prasad'),
  ('SEED-2023-06-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2023-06-15', 'Ponugoti Prasad'),
  ('SEED-2023-07-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2023-07-15', 'Ponugoti Prasad'),
  ('SEED-2023-08-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2023-08-15', 'Ponugoti Prasad'),
  ('SEED-2023-09-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2023-09-15', 'Ponugoti Prasad'),
  ('SEED-2023-10-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2023-10-15', 'Ponugoti Prasad'),
  ('SEED-2023-11-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2023-11-15', 'Ponugoti Prasad'),
  ('SEED-2023-12-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2023-12-15', 'Ponugoti Prasad'),
  ('SEED-2023-04-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2023-04-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2023-06-SAM', 1000.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2023-06-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2023-09-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2023-09-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2023-11-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2023-11-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2023-01-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2023-01-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2023-02-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2023-02-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2023-03-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2023-03-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2023-05-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2023-05-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2023-06-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2023-06-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2023-07-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2023-07-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2023-08-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2023-08-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2023-09-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2023-09-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2023-10-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2023-10-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2023-11-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2023-11-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2023-12-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2023-12-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2023-01-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2023-01-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2023-06-SRR', 2500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2023-06-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2023-10-SRR', 2000.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2023-10-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2023-11-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2023-11-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2023-12-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2023-12-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2023-01-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2023-01-15', 'Kollai Venkateswarlu'),
  ('SEED-2023-02-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2023-02-15', 'Kollai Venkateswarlu'),
  ('SEED-2023-03-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2023-03-15', 'Kollai Venkateswarlu'),
  ('SEED-2023-06-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2023-06-15', 'Kollai Venkateswarlu'),
  ('SEED-2023-07-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2023-07-15', 'Kollai Venkateswarlu'),
  ('SEED-2023-08-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2023-08-15', 'Kollai Venkateswarlu'),
  ('SEED-2023-09-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2023-09-15', 'Kollai Venkateswarlu'),
  ('SEED-2023-10-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2023-10-15', 'Kollai Venkateswarlu'),
  ('SEED-2023-11-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2023-11-15', 'Kollai Venkateswarlu'),
  ('SEED-2023-12-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2023-12-15', 'Kollai Venkateswarlu'),
  ('SEED-2023-02-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2023-02-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2023-03-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2023-03-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2023-04-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2023-04-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2023-05-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2023-05-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2023-06-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2023-06-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2023-07-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2023-07-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2023-08-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2023-08-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2023-09-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2023-09-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2023-10-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2023-10-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2023-11-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2023-11-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2023-05-TRN', 500.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2023-05-15', 'Panditi Trinath Gupta'),
  ('SEED-2023-07-TRN', 500.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2023-07-15', 'Panditi Trinath Gupta'),
  ('SEED-2023-09-TRN', 1000.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2023-09-15', 'Panditi Trinath Gupta'),
  ('SEED-2023-10-TRN', 1000.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2023-10-15', 'Panditi Trinath Gupta'),
  ('SEED-2023-02-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2023-02-15', 'Koppavarapu Sudhakar'),
  ('SEED-2023-05-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2023-05-15', 'Koppavarapu Sudhakar'),
  ('SEED-2023-07-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2023-07-15', 'Koppavarapu Sudhakar'),
  ('SEED-2023-09-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2023-09-15', 'Koppavarapu Sudhakar'),
  ('SEED-2023-12-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2023-12-15', 'Koppavarapu Sudhakar')
on conflict (transaction_id) do nothing;

-- 2) Bank interest (1 rows)
insert into public.transactions
  (transaction_id, amount, contribution_type, interest_source, member_id, transaction_date, description) values
  ('SEED-BANK-2023-11', 600.00, 'interest', 'bank', null, '2023-11-28', 'Bank interest credited')
on conflict (transaction_id) do nothing;

commit;

-- Sanity check (uncomment to run after insert):
-- select contribution_type, interest_source, count(*), sum(amount)
--   from public.transactions
--  where transaction_date >= '2023-01-01' and transaction_date < '2024-01-01'
--  group by 1, 2 order by 1, 2;
