-- =============================================================================
-- FCF Tracker — 2024 transactions seed
-- Source: '2024' sheet of FCF Latest one upto 6_07_2020.xlsx
--
-- Generated by scripts/generate-yearly-transactions.py — do not hand-edit.
-- Re-running is safe: every INSERT uses ON CONFLICT (transaction_id) DO NOTHING.
--
-- Rows: 123  (117 contributions + 6 bank-int + 0 loan-int)
-- Totals: contributions=₹65,800.00  bank_interest=₹8,600.00  loan_interest=₹0.00
--
-- member_id is resolved at INSERT time via the canonical email so this
-- works even after a clean DB rebuild (UUIDs change; emails don't).
-- =============================================================================

begin;

-- 1) Member contributions (117 rows)
insert into public.transactions
  (transaction_id, amount, transaction_type, interest_source, member_id, transaction_date, description) values
  ('SEED-2024-01-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2024-01-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2024-02-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2024-02-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2024-03-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2024-03-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2024-04-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2024-04-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2024-05-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2024-05-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2024-06-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2024-06-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2024-07-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2024-07-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2024-08-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2024-08-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2024-09-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2024-09-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2024-10-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2024-10-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2024-11-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2024-11-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2024-12-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2024-12-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2024-05-RAM', 1000.00, 'contribution', null, (select id from public.members where email = 'anjimca48@gmail.com'), '2024-05-15', 'Chittiboyina Ramanjaneyulu'),
  ('SEED-2024-01-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2024-01-15', 'Chintalapalli Srinith'),
  ('SEED-2024-02-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2024-02-15', 'Chintalapalli Srinith'),
  ('SEED-2024-03-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2024-03-15', 'Chintalapalli Srinith'),
  ('SEED-2024-04-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2024-04-15', 'Chintalapalli Srinith'),
  ('SEED-2024-05-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2024-05-15', 'Chintalapalli Srinith'),
  ('SEED-2024-06-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2024-06-15', 'Chintalapalli Srinith'),
  ('SEED-2024-07-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2024-07-15', 'Chintalapalli Srinith'),
  ('SEED-2024-08-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2024-08-15', 'Chintalapalli Srinith'),
  ('SEED-2024-09-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2024-09-15', 'Chintalapalli Srinith'),
  ('SEED-2024-10-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2024-10-15', 'Chintalapalli Srinith'),
  ('SEED-2024-11-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2024-11-15', 'Chintalapalli Srinith'),
  ('SEED-2024-12-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2024-12-15', 'Chintalapalli Srinith'),
  ('SEED-2024-01-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2024-01-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2024-02-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2024-02-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2024-03-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2024-03-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2024-04-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2024-04-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2024-05-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2024-05-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2024-06-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2024-06-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2024-07-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2024-07-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2024-09-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2024-09-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2024-10-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2024-10-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2024-11-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2024-11-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2024-12-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2024-12-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2024-02-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2024-02-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2024-03-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2024-03-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2024-06-DLN', 1000.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2024-06-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2024-08-DLN', 500.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2024-08-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2024-01-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2024-01-15', 'Korrakuti Paramesh'),
  ('SEED-2024-02-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2024-02-15', 'Korrakuti Paramesh'),
  ('SEED-2024-03-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2024-03-15', 'Korrakuti Paramesh'),
  ('SEED-2024-04-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2024-04-15', 'Korrakuti Paramesh'),
  ('SEED-2024-05-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2024-05-15', 'Korrakuti Paramesh'),
  ('SEED-2024-06-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2024-06-15', 'Korrakuti Paramesh'),
  ('SEED-2024-07-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2024-07-15', 'Korrakuti Paramesh'),
  ('SEED-2024-08-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2024-08-15', 'Korrakuti Paramesh'),
  ('SEED-2024-09-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2024-09-15', 'Korrakuti Paramesh'),
  ('SEED-2024-10-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2024-10-15', 'Korrakuti Paramesh'),
  ('SEED-2024-11-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2024-11-15', 'Korrakuti Paramesh'),
  ('SEED-2024-12-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2024-12-15', 'Korrakuti Paramesh'),
  ('SEED-2024-01-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2024-01-15', 'Ponugoti Prasad'),
  ('SEED-2024-02-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2024-02-15', 'Ponugoti Prasad'),
  ('SEED-2024-03-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2024-03-15', 'Ponugoti Prasad'),
  ('SEED-2024-05-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2024-05-15', 'Ponugoti Prasad'),
  ('SEED-2024-07-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2024-07-15', 'Ponugoti Prasad'),
  ('SEED-2024-08-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2024-08-15', 'Ponugoti Prasad'),
  ('SEED-2024-09-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2024-09-15', 'Ponugoti Prasad'),
  ('SEED-2024-10-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2024-10-15', 'Ponugoti Prasad'),
  ('SEED-2024-11-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2024-11-15', 'Ponugoti Prasad'),
  ('SEED-2024-12-PRS', 500.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2024-12-15', 'Ponugoti Prasad'),
  ('SEED-2024-02-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2024-02-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2024-03-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2024-03-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2024-06-SAM', 3300.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2024-06-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2024-08-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2024-08-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2024-10-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2024-10-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2024-11-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2024-11-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2024-12-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2024-12-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2024-01-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2024-01-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2024-02-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2024-02-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2024-03-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2024-03-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2024-04-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2024-04-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2024-05-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2024-05-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2024-06-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2024-06-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2024-07-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2024-07-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2024-08-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2024-08-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2024-09-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2024-09-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2024-10-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2024-10-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2024-11-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2024-11-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2024-12-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2024-12-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2024-03-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2024-03-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2024-05-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2024-05-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2024-06-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2024-06-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2024-08-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2024-08-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2024-09-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2024-09-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2024-10-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2024-10-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2024-11-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2024-11-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2024-12-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2024-12-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2024-01-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2024-01-15', 'Kollai Venkateswarlu'),
  ('SEED-2024-03-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2024-03-15', 'Kollai Venkateswarlu'),
  ('SEED-2024-05-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2024-05-15', 'Kollai Venkateswarlu'),
  ('SEED-2024-06-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2024-06-15', 'Kollai Venkateswarlu'),
  ('SEED-2024-07-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2024-07-15', 'Kollai Venkateswarlu'),
  ('SEED-2024-08-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2024-08-15', 'Kollai Venkateswarlu'),
  ('SEED-2024-11-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2024-11-15', 'Kollai Venkateswarlu'),
  ('SEED-2024-12-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2024-12-15', 'Kollai Venkateswarlu'),
  ('SEED-2024-12-VSW', 1000.00, 'contribution', null, (select id from public.members where email = 'viswanath.mca0688@gmail.com'), '2024-12-15', 'Oleti Viswanath'),
  ('SEED-2024-01-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2024-01-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2024-03-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2024-03-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2024-05-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2024-05-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2024-08-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2024-08-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2024-09-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2024-09-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2024-10-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2024-10-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2024-11-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2024-11-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2024-12-LXM', 500.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2024-12-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2024-08-TRN', 1000.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2024-08-15', 'Panditi Trinath Gupta'),
  ('SEED-2024-11-TRN', 1500.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2024-11-15', 'Panditi Trinath Gupta'),
  ('SEED-2024-02-SUD', 1000.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2024-02-15', 'Koppavarapu Sudhakar'),
  ('SEED-2024-03-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2024-03-15', 'Koppavarapu Sudhakar'),
  ('SEED-2024-05-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2024-05-15', 'Koppavarapu Sudhakar'),
  ('SEED-2024-07-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2024-07-15', 'Koppavarapu Sudhakar'),
  ('SEED-2024-08-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2024-08-15', 'Koppavarapu Sudhakar'),
  ('SEED-2024-09-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2024-09-15', 'Koppavarapu Sudhakar'),
  ('SEED-2024-10-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2024-10-15', 'Koppavarapu Sudhakar'),
  ('SEED-2024-11-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2024-11-15', 'Koppavarapu Sudhakar'),
  ('SEED-2024-12-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2024-12-15', 'Koppavarapu Sudhakar')
on conflict (transaction_id) do nothing;

-- 2) Bank interest (6 rows)
insert into public.transactions
  (transaction_id, amount, transaction_type, interest_source, member_id, transaction_date, description) values
  ('SEED-BANK-2024-02', 600.00, 'interest', 'bank', null, '2024-02-28', 'Bank interest credited'),
  ('SEED-BANK-2024-03', 5600.00, 'interest', 'bank', null, '2024-03-28', 'Bank interest credited'),
  ('SEED-BANK-2024-08', 600.00, 'interest', 'bank', null, '2024-08-28', 'Bank interest credited'),
  ('SEED-BANK-2024-10', 600.00, 'interest', 'bank', null, '2024-10-28', 'Bank interest credited'),
  ('SEED-BANK-2024-11', 600.00, 'interest', 'bank', null, '2024-11-28', 'Bank interest credited'),
  ('SEED-BANK-2024-12', 600.00, 'interest', 'bank', null, '2024-12-28', 'Bank interest credited')
on conflict (transaction_id) do nothing;

commit;

-- Sanity check (uncomment to run after insert):
-- select transaction_type, interest_source, count(*), sum(amount)
--   from public.transactions
--  where transaction_date >= '2024-01-01' and transaction_date < '2025-01-01'
--  group by 1, 2 order by 1, 2;
