-- =============================================================================
-- FCF Tracker — 2026 transactions seed
-- Source: '2026' sheet of FCF Latest one upto 6_07_2020.xlsx
--
-- Generated by scripts/generate-yearly-transactions.py — do not hand-edit.
-- Re-running is safe: every INSERT uses ON CONFLICT (transaction_id) DO NOTHING.
--
-- Rows: 64  (60 contributions + 4 bank-int)
-- Totals: contributions=₹35,900.00  bank_interest=₹2,303.00
--
-- Loan interest for 2026 (₹10,900) used to live here as five SEED-LOAN-2026-MM
-- rows. They have moved to scripts/prod/loan-interest.sql, which attaches each
-- payment to its loan_id. Do not re-add them here or both files will run and
-- the loan-interest total will double-count.
--
-- member_id is resolved at INSERT time via the canonical email so this
-- works even after a clean DB rebuild (UUIDs change; emails don't).
-- =============================================================================

begin;

-- 1) Member contributions (60 rows)
insert into public.transactions
  (transaction_id, amount, transaction_type, interest_source, member_id, transaction_date, description) values
  ('SEED-2026-01-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2026-01-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2026-02-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2026-02-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2026-03-ANL', 500.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2026-03-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2026-05-ANL', 1000.00, 'contribution', null, (select id from public.members where email = 'anil.kothacheruvu@gmail.com'), '2026-05-15', 'Kothacheruvu Anil Kumar Reddy'),
  ('SEED-2026-01-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2026-01-15', 'Chintalapalli Srinith'),
  ('SEED-2026-02-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2026-02-15', 'Chintalapalli Srinith'),
  ('SEED-2026-03-SNT', 500.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2026-03-15', 'Chintalapalli Srinith'),
  ('SEED-2026-05-SNT', 1000.00, 'contribution', null, (select id from public.members where email = 'srimca67@gmail.com'), '2026-05-15', 'Chintalapalli Srinith'),
  ('SEED-2026-01-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2026-01-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2026-02-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2026-02-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2026-03-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2026-03-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2026-04-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2026-04-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2026-05-CHL', 500.00, 'contribution', null, (select id from public.members where email = 'venkat.0082@gmail.com'), '2026-05-15', 'Rallabandi Venkata Narasimha Charlu'),
  ('SEED-2026-01-DLN', 750.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2026-01-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2026-02-DLN', 750.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2026-02-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2026-03-DLN', 750.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2026-03-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2026-04-DLN', 750.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2026-04-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2026-05-DLN', 750.00, 'contribution', null, (select id from public.members where email = 'dlnarayana.mca29@gmail.com'), '2026-05-15', 'Darisiguntla Lakshmi Narayana'),
  ('SEED-2026-01-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2026-01-15', 'Korrakuti Paramesh'),
  ('SEED-2026-02-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2026-02-15', 'Korrakuti Paramesh'),
  ('SEED-2026-03-PAR', 500.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2026-03-15', 'Korrakuti Paramesh'),
  ('SEED-2026-05-PAR', 1000.00, 'contribution', null, (select id from public.members where email = 'paramesh.java5@gmail.com'), '2026-05-15', 'Korrakuti Paramesh'),
  ('SEED-2026-01-PRS', 750.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2026-01-15', 'Ponugoti Prasad'),
  ('SEED-2026-02-PRS', 750.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2026-02-15', 'Ponugoti Prasad'),
  ('SEED-2026-03-PRS', 750.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2026-03-15', 'Ponugoti Prasad'),
  ('SEED-2026-04-PRS', 750.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2026-04-15', 'Ponugoti Prasad'),
  ('SEED-2026-05-PRS', 750.00, 'contribution', null, (select id from public.members where email = 'prasadnaidu271985@gmail.com'), '2026-05-15', 'Ponugoti Prasad'),
  ('SEED-2026-01-SAM', 500.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2026-01-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2026-05-SAM', 1000.00, 'contribution', null, (select id from public.members where email = 'sambamca06@gmail.com'), '2026-05-15', 'Bollam Samba Siva Reddy'),
  ('SEED-2026-01-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2026-01-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2026-02-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2026-02-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2026-03-SDP', 500.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2026-03-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2026-05-SDP', 1000.00, 'contribution', null, (select id from public.members where email = 'sandeep.mca56@gmail.com'), '2026-05-15', 'Biddala Sandeep Kumar Reddy'),
  ('SEED-2026-01-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2026-01-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2026-02-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2026-02-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2026-03-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2026-03-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2026-04-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2026-04-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2026-05-SRR', 500.00, 'contribution', null, (select id from public.members where email = 'sreemca65@gmail.com'), '2026-05-15', 'Duggireddy Srinath Reddy'),
  ('SEED-2026-02-MED', 500.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2026-02-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2026-03-MED', 500.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2026-03-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2026-04-MED', 500.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2026-04-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2026-05-MED', 500.00, 'contribution', null, (select id from public.members where email = 'sunilreddy.meda@gmail.com'), '2026-05-15', 'Meda Sunil Kumar Reddy'),
  ('SEED-2026-01-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2026-01-15', 'Kollai Venkateswarlu'),
  ('SEED-2026-02-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2026-02-15', 'Kollai Venkateswarlu'),
  ('SEED-2026-03-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2026-03-15', 'Kollai Venkateswarlu'),
  ('SEED-2026-04-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2026-04-15', 'Kollai Venkateswarlu'),
  ('SEED-2026-05-VEN', 500.00, 'contribution', null, (select id from public.members where email = 'venky.kollai@gmail.com'), '2026-05-15', 'Kollai Venkateswarlu'),
  ('SEED-2026-01-LXM', 600.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2026-01-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2026-02-LXM', 600.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2026-02-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2026-03-LXM', 600.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2026-03-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2026-04-LXM', 600.00, 'contribution', null, (select id from public.members where email = 'lakshmi.talk6@gmail.com'), '2026-04-15', 'Thummalapalli Guru Prasanna Lakshmi'),
  ('SEED-2026-01-TRN', 500.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2026-01-15', 'Panditi Trinath Gupta'),
  ('SEED-2026-02-TRN', 500.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2026-02-15', 'Panditi Trinath Gupta'),
  ('SEED-2026-03-TRN', 500.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2026-03-15', 'Panditi Trinath Gupta'),
  ('SEED-2026-04-TRN', 500.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2026-04-15', 'Panditi Trinath Gupta'),
  ('SEED-2026-05-TRN', 500.00, 'contribution', null, (select id from public.members where email = 'trinathgupta.p@gmail.com'), '2026-05-15', 'Panditi Trinath Gupta'),
  ('SEED-2026-01-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2026-01-15', 'Koppavarapu Sudhakar'),
  ('SEED-2026-02-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2026-02-15', 'Koppavarapu Sudhakar'),
  ('SEED-2026-03-SUD', 500.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2026-03-15', 'Koppavarapu Sudhakar'),
  ('SEED-2026-05-SUD', 1000.00, 'contribution', null, (select id from public.members where email = 'sudhakar487248@gmail.com'), '2026-05-15', 'Koppavarapu Sudhakar')
on conflict (transaction_id) do nothing;

-- 2) Bank interest (4 rows)
insert into public.transactions
  (transaction_id, amount, transaction_type, interest_source, member_id, transaction_date, description) values
  ('SEED-BANK-2026-01', 535.00, 'interest', 'bank', null, '2026-01-28', 'Bank interest credited'),
  ('SEED-BANK-2026-02', 548.00, 'interest', 'bank', null, '2026-02-28', 'Bank interest credited'),
  ('SEED-BANK-2026-03', 647.00, 'interest', 'bank', null, '2026-03-28', 'Bank interest credited'),
  ('SEED-BANK-2026-04', 573.00, 'interest', 'bank', null, '2026-04-28', 'Bank interest credited')
on conflict (transaction_id) do nothing;

commit;

-- Sanity check (uncomment to run after insert):
-- select transaction_type, interest_source, count(*), sum(amount)
--   from public.transactions
--  where transaction_date >= '2026-01-01' and transaction_date < '2027-01-01'
--  group by 1, 2 order by 1, 2;
